# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 13:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_added_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_added_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
