# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_auto_20160510_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_avatar',
            field=models.ImageField(max_length=255, upload_to=b''),
        ),
    ]
