# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_auto_20160510_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liked_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_pressed', models.BooleanField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Answer')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='liked',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Liked',
        ),
    ]
