# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0004_auto_20160510_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags_answer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='liked_question',
            name='answer',
        ),
        migrations.AddField(
            model_name='liked_question',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ask.Question'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tags_question',
            name='question',
        ),
        migrations.AddField(
            model_name='tags_question',
            name='question',
            field=models.ManyToManyField(to='ask.Question'),
        ),
        migrations.DeleteModel(
            name='Tags_Answer',
        ),
    ]
