# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 12:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask', '0005_auto_20160517_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_login',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_surname',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
