# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0007_auto_20160517_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags_question',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='question_tag',
            field=models.ManyToManyField(to='ask.Tags_Question'),
        ),
    ]
