# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0008_auto_20160521_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_title',
        ),
    ]
